version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace/api:cached
        # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/data
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: data
